name: Deploy NuxtJS to GitHub Pages

on:
  push:
    branches:
      - main # Замените на вашу основную ветку, если она отличается

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Укажите версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build for GitHub Pages
        run: NUXT_APP_BASE_URL=/stickerBoard/ npx nuxt build --preset github_pages # Замените на ваш репозиторий

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/public # Путь к сгенерированным статическим файлам
